version: "3.8"
services:
  postgres:
    image: postgres
    restart: always
    ports:
      - "9902:5432"
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
  pgadmin:
    image: dpage/pgadmin4:4.25
    restart: always
    depends_on:
      - postgres
    ports:
      - "9903:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_USER}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD}
    links:
      - postgres
